import { AuthProvider } from '@/shared/contexts';
import Footer from '@/widgets/Footer/footer';
import Header from '@/widgets/Header/header';
import type { Metadata } from 'next';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col page-container">
          <AuthProvider>
            <Header />
            {children}
            <ToastContainer position="top-center" autoClose={2000} />
            <Footer />
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
