import Footer from '@/widgets/Footer/footer';
import Header from '@/widgets/Header/header';
import type { Metadata } from 'next';
import './globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col page-container">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
